MY_TARGET  :=  $(FIXTURES_RELEASE_DIR)/screen.js
MY_STATIC_TARGET  :=
MY_TARGETDIR := $(FIXTURES_BUILD_DIR)
MY_SRCDIR :=  $(FIXTURES_DIR)/screen

ifeq ($(call FINDINLIST,$(MY_TARGET),$(ALL)),1)

MY_SRCS := \
	screen.js\

MY_INCLUDES :=
MY_CFLAGS := 
MY_CPPFLAGS := 
MY_LINKSCRIPT := 

include make/js_lib.mk

endif
